services:
  - type: web
    name: mosdotbriut
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: HOST
        value: 0.0.0.0
